### ISSUE TITLE
Loading of voc.txt takes too long

### ISSUE THREAD

**Issue by paul-michalik** [paul-michalik/ORB_SLAM2#18]
Loading of the BoW vocabulary must be accelerated. Investigate possibilities to accomplish this.

**Comment by shanmukhananda** [comment]
Current numbers on my PC (i7, 4cores-8threads, 2.6GHz, 16GB RAM)
Windows Release build takes 40-42 seconds to load orb-voc, (8 cores, 16gb RAM)
Ubuntu Release build takes 7-9 seconds to load orb-voc (4 cores, 8gb RAM)

Ideas on improving
- Use binary vocabulary instead of txt file.
- In windows we have to remove /RTC and try /O2. (VS optimization flags). Linux optimization flags are already in place

**Comment by shanmukhananda** [comment]
Tried with binary vocabulary referring [this link](https://github.com/raulmur/ORB_SLAM2/pull/21)
Vocabulary loading time now reduces to 350-450ms both in linux and windows.

**Comment by shanmukhananda** [comment]
changes merged cf74e99f6c1fc6d46fb309b19f4bc1a93c77b1e7
